/*
 * Copyright (C) Sportradar AG. See LICENSE for full license governing this code
 */
package com.sportradar.unifiedodds.sdk.entities.custombet;

import java.util.Date;
import java.util.List;

/**
 * Represents prebuilt bets response
 */
public interface PrebuiltBets {
    /**
     * Returns the list of event recommendations
     *
     * @return the list of event recommendations
     */
    List<EventRecommendations> getEvents();

    /**
     * Returns the number of requested recommendations
     *
     * @return the number of requested recommendations
     */
    int getRequestedRecommendations();

    /**
     * Returns the date and time when the response was generated by the server
     *
     * @return the date/time when generated, or null if not available
     */
    Date getGeneratedAt();
}
