<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  <betstop_reasons_descriptions response_code="OK">
    <betstop_reason id="0" description="UNKNOWN"/>
    <betstop_reason id="1" description="POSSIBLE_GOAL"/>
    <betstop_reason id="2" description="POSSIBLE_RED_CARD"/>
    <betstop_reason id="3" description="SCOUT_LOST"/>
    <betstop_reason id="4" description="POSSIBLE_GOAL_HOME"/>
    <betstop_reason id="5" description="POSSIBLE_GOAL_AWAY"/>
    <betstop_reason id="6" description="POSSIBLE_RED_CARD_HOME"/>
    <betstop_reason id="7" description="POSSIBLE_RED_CARD_AWAY"/>
    <betstop_reason id="8" description="POSSIBLE_PENALTY"/>
    <betstop_reason id="9" description="POSSIBLE_PENALTY_HOME"/>
    <betstop_reason id="10" description="POSSIBLE_PENALTY_AWAY"/>
    <betstop_reason id="11" description="CONNECTED_TO_SUPERVISOR"/>
    <betstop_reason id="12" description="MATCH_ENDED"/>
    <betstop_reason id="13" description="GAMEPOINT"/>
    <betstop_reason id="14" description="TIEBREAK"/>
    <betstop_reason id="15" description="POSSIBLE_DIRECT_FOUL_HOME"/>
    <betstop_reason id="16" description="POSSIBLE_DIRECT_FOUL_AWAY"/>
    <betstop_reason id="17" description="POSSIBLE_DIRECT_FOUL"/>
    <betstop_reason id="18" description="DANGEROUS_FREE_KICK_HOME"/>
    <betstop_reason id="19" description="DANGEROUS_FREE_KICK_AWAY"/>
    <betstop_reason id="20" description="DANGEROUS_GOAL_POSITION_HOME"/>
    <betstop_reason id="21" description="DANGEROUS_GOAL_POSITION_AWAY"/>
    <betstop_reason id="22" description="GOAL_UNDER_REVIEW"/>
    <betstop_reason id="23" description="SCORE_UNDER_REVIEW"/>
    <betstop_reason id="24" description="DISCONNECTION"/>
    <betstop_reason id="25" description="POSSIBLE_CHECKOUT"/>
    <betstop_reason id="26" description="MULTIPLE_SUSPENSIONS"/>
    <betstop_reason id="27" description="POSSIBLE_DANGEROUS_FREE_KICK"/>
    <betstop_reason id="28" description="POSSIBLE_DANGEROUS_GOAL_POSITION"/>
    <betstop_reason id="29" description="POSSIBLE_TOUCHDOWN_HOME"/>
    <betstop_reason id="30" description="POSSIBLE_TOUCHDOWN_AWAY"/>
    <betstop_reason id="31" description="POSSIBLE_FIELDGOAL_HOME"/>
    <betstop_reason id="32" description="POSSIBLE_FIELDGOAL_AWAY"/>
    <betstop_reason id="33" description="POSSIBLE_SAFETY_HOME"/>
    <betstop_reason id="34" description="POSSIBLE_SAFETY_AWAY"/>
    <betstop_reason id="35" description="POSSIBLE_TURNOVER_HOME"/>
    <betstop_reason id="36" description="POSSIBLE_TURNOVER_AWAY"/>
    <betstop_reason id="37" description="VIDEO_REVIEW"/>
    <betstop_reason id="38" description="REDZONE_HOME"/>
    <betstop_reason id="39" description="REDZONE_AWAY"/>
    <betstop_reason id="40" description="POSSIBLE_BOUNDARY"/>
    <betstop_reason id="41" description="POSSIBLE_WICKET"/>
    <betstop_reason id="42" description="POSSIBLE_CHALLENGE_HOME"/>
    <betstop_reason id="43" description="POSSIBLE_CHALLENGE_AWAY"/>
    <betstop_reason id="44" description="POSSIBLE_TURNOVER"/>
    <betstop_reason id="45" description="UNKNOWN_OPERATOR"/>
    <betstop_reason id="46" description="FREEBALL"/>
    <betstop_reason id="47" description="DEEP_BALL"/>
    <betstop_reason id="48" description="POSSIBLE_RUN"/>
    <betstop_reason id="49" description="MAINTENANCE"/>
    <betstop_reason id="50" description="BASE_HIT_DELETED"/>
    <betstop_reason id="51" description="MATCH_DELAYED"/>
    <betstop_reason id="52" description="MATCH_POSTPONED"/>
    <betstop_reason id="53" description="SCOUT_DISCONNECTION_TV_SIGNAL"/>
    <betstop_reason id="54" description="POSSIBLE_PENALTY_OFFSETTING"/>
    <betstop_reason id="55" description="POSSIBLE_PUNT_HOME"/>
    <betstop_reason id="56" description="POSSIBLE_PUNT_AWAY"/>
    <betstop_reason id="57" description="POSSIBLE_FOURTH_DOWN_ATTEMPT_HOME"/>
    <betstop_reason id="58" description="POSSIBLE_FOURTH_DOWN_ATTEMPT_AWAY"/>
    <betstop_reason id="59" description="POSSIBLE_ONSIDE_KICK_HOME"/>
    <betstop_reason id="60" description="POSSIBLE_ONSIDE_KICK_AWAY"/>
    <betstop_reason id="61" description="POSSIBLE_CHALLENGE"/>
    <betstop_reason id="62" description="POSSIBLE_CARD"/>
    <betstop_reason id="63" description="DELAYED_PENALTY"/>
    <betstop_reason id="64" description="SHOOTOUT_BEGINS"/>
    <betstop_reason id="65" description="EMPTY_NET"/>
    <betstop_reason id="66" description="POSSIBLE_TRY_HOME"/>
    <betstop_reason id="67" description="POSSIBLE_TRY_AWAY"/>
    <betstop_reason id="68" description="POSSIBLE_DROP_GOAL_HOME"/>
    <betstop_reason id="69" description="POSSIBLE_DROP_GOAL_AWAY"/>
    <betstop_reason id="70" description="POSSIBLE_CARD_HOME"/>
    <betstop_reason id="71" description="POSSIBLE_CARD_AWAY"/>
    <betstop_reason id="72" description="POSSIBLE_PENALTY_HOME_HOCKEY"/>
    <betstop_reason id="73" description="POSSIBLE_PENALTY_AWAY_HOCKEY"/>
    <betstop_reason id="74" description="DELAYED_PENALTY_HOME_HOCKEY"/>
    <betstop_reason id="75" description="DELAYED_PENALTY_AWAY_HOCKEY"/>
    <betstop_reason id="76" description="TWO_MAN_ADVANTAGE_HOME"/>
    <betstop_reason id="77" description="TWO_MAN_ADVANTAGE_AWAY"/>
    <betstop_reason id="78" description="POSSIBLE_FIELD_GOAL"/>
    <betstop_reason id="79" description="ROLLBACK_EVENT"/>
    <betstop_reason id="80" description="POSSIBLE_DROP_KICK_HOME"/>
    <betstop_reason id="81" description="POSSIBLE_DROP_KICK_AWAY"/>
    <betstop_reason id="82" description="POSSIBLE_DROP_KICK"/>
    <betstop_reason id="83" description="POSSIBLE_VIDEO_ASSISTANT_REFEREE"/>
    <betstop_reason id="84" description="FEED_INTERRUPTION"/>
    <betstop_reason id="85" description="POSSIBLE_SCORE"/>
    <betstop_reason id="86" description="POSSIBLE_SCORE_HOME"/>
    <betstop_reason id="87" description="POSSIBLE_SCORE_AWAY"/>
    <betstop_reason id="88" description="POSSIBLE_VIDEO_ASSISTANT_REFEREE_HOME"/>
    <betstop_reason id="89" description="POSSIBLE_VIDEO_ASSISTANT_REFEREE_AWAY"/>
  </betstop_reasons_descriptions>